### ISSUE TITLE
Crypto and Node.js Dependencies?

### ISSUE THREAD

**Issue by suxur** [factsfinder/Zeus#1]
How are you handling Node.js packages in React Native? Anytime I try to use the Stellar SDK in a React Native app I getting the error:

Requiring unknown module "crypto”

**Comment by LiamDotPro** [comment]
Sounds like you need to install a cross peer dependency for the SDK to function

**Comment by factsfinder** [comment]
@suxur Try this => https://www.npmjs.com/package/react-native-crypto
if npm hangs, use yarn.

**Comment by factsfinder** [comment]
@suxur I've updated the repo with dependencies that will solve the issues you're facing. Fork and clone and check it out.
